config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about", as: "about"
  get "search" => "searches#search"
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources:book_comments,only:[:create,:destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
   end
   
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites, dependent: :destroy
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  has_one_attached :profile_image

  validates :name, presence: true
  validates :name, length: {in: 2..20}
  validates :name, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [width, height]).processed
  end
  
  def follow(user_id)
   relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
   relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
   followings.include?(user)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @users = User.all
    @user = User.find(params[:id])
    @newbook = Book.new
    @books = @user.books
  end

  def index
    @user = current_user
    @users = User.all
    @newbook = Book.new
    @books = Book.all
  end


  def edit
    is_matching_login_user
    @user = User.find(params[:id])
  end

  def update
    is_matching_login_user
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "Update successfully"
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

   private

  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def is_matching_login_user
    user_id = params[:id].to_i
    login_user_id = current_user.id
    if(user_id != login_user_id)
      redirect_to user_path(current_user.id)
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_user.html.erb
<table class="table table-user">
  <thead>
    <tr>
      <%= image_tag user.get_profile_image(100,100), fallback: "no_image.jpg" %>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>Introduction</th>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>フォロー数:</th>
      <th><%= user.followings.count %></th>
    </tr>
    <tr>
      <th>フォロワー数:</th>
      <th><%= user.followers.count %></th>
    </tr>
    <tr>
      <th><%= render 'relationships/followbutan', user: user %></th>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

          <h2>User info</h2>

          <% if @user.errors.any? %>
            <%= @user.errors.count %>error
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          <% end %>

          <%= form_with model: @user do |f| %>
            <p>Name</p>
              <%= f.text_field :name, autofocus: true %>
            <p>Image</p>
              <%= f.file_field :profile_image, accept: "image/*" %>
            <p>Introduction</p>
              <%= f.text_field :introduction %><br>
            <%= f.submit 'Update User', class: 'btn btn-secondary' %>
          <% end %>

        </div>
      </div>
    </div>
</main>

app/views/users/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

      <h1>User info</h1>
        <%= render 'users/user', user: @user %>

      <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block', method: :get do %>
        <i class="fas fa-user-cog"></i>
      <% end %>

      <h3>New book</h3>
        <%= render 'books/book', book: @newbook %>
      </div>

      <div class="col-md-8 offset-md-1">
        <table class="table table-hover table-inverse">
          <h4>Users</h4>
          <thead>
            <th>image </th>
            <th>name </th>
              <tr>
              <% @users.each do |user| %>
                <tr>
                  <th>
                      <%= image_tag user.get_profile_image(100,100), fallback: "no_image.jpg" %>
                  </th>
                  <th><%= user.name %></th>
                  <th>フォロー数:</th>
                  <th><%= user.followings.count %></th>
                  <th>フォロワー数:</th>
                  <th><%= user.followers.count %></th>
                  <th><%= render 'relationships/followbutan', user: user %></th>
                  <th><%= link_to "Show", user_path(user.id) %></th>
                </tr>
              <% end %>
              </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h1>User info</h1>
          <%= render 'users/user', user: @user %>

        <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block', method: :get do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
        <p></p>

        <h3>New book</h3>
          <%= render 'books/book', book: @newbook %>
      </div>

      <div class="col-md-8 offset-md-1">
        <table class="table table-hover table-inverse">
          <h4>Books</h4>
          <thead>
            <th></th>
            <th>Title </th>
            <th>Opinion </th>
            <th colspan="3"></th>
            <tr></tr>
            <tr>
              <% @books.each do |book| %>
              <tr>
                <th>
                  <%= link_to user_path(@user.id) do %>
                    <%= image_tag @user.get_profile_image(100,100), fallback: "no_image.jpg" %>
                  <% end %>
                </th>
                <th><%= link_to book.title, book_path(book.id) %></th>
                <th><%= book.body %></th>
              </tr>
              <% end %>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>
</main>