config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'relationships/followings'
  get 'relationships/followers'
  devise_for :users
  root to: "homes#top"
  get "home/about"=>"homes#about", as: "about"
  get "search" => "searches#search"
  
  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources:book_comments,only:[:create,:destroy]
  end
  
  resources :users, only: [:index,:show,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
   end
   
end

app/models/book.rb
class Book < ApplicationRecord

  has_one_attached :image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  
  validates :title, presence: true
  validates :body, presence: true
  validates :body, length: {maximum: 200}

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image
  end
  
  def favorited?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
  
  def self.looks(search, word)
    if search == "perfect_match"
      @book = Book.where("title LIKE?","#{word}")
    elsif search == "forward_match"
      @book = Book.where("title LIKE?","#{word}%")
    elsif search == "backward_match"
      @book = Book.where("title LIKE?","%#{word}")
    elsif search == "partial_match"
      @book = Book.where("title LIKE?","%#{word}%")
    else
      @book = Book.all
    end
  end
  
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Posting successfully"
      redirect_to book_path(@book.id)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
    @books = Book.all
  end

  def show
    @newbook = Book.new
    @book = Book.find(params[:id])
    @user = @book.user
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @books = Book.all
    if @book.user.id != current_user.id
     redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    @book.user_id == current_user.id
    if @book.update(book_params)
      flash[:notice] = "Update successfully"
      redirect_to book_path(@book.id)
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      flash[:notice] = "Destroy successfully"
      redirect_to books_path
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<%= form_with model: book do |f| %>
  <p>Title</p>
    <%= f.text_field :title %>
  <p>Opinion</p>
    <%= f.text_area :body %>
  <%= f.submit 'Create Book', class: 'btn btn-success' %>
<% end %>

app/views/books/edit.html.erb
<main>
 <p id="notice"></p>
  <div class="container">
    <div class="row">
      <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

        <h2>Editing Book</h2>

        <% if @book.errors.any? %>
          <%= @book.errors.count %>errors
          <ul>
            <% @book.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

          <%= form_with model: @book do |f| %>
            <p>Title</p>
              <%=f.text_field :title %>
            <p>Opinion</p>
              <%= f.text_area :body %><br>
            <%= f.submit 'Update Book', class: 'btn btn-success' %>
          <% end %>
        <%= link_to "Show", book_path %>
        <%= link_to "Back", books_path %>

      </div>
    </div>
  </div>
</main>

app/views/books/index.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">

        <% if @book.errors.any? %>
          <%= @book.errors.count %>error
            <ul>
              <% @book.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
        <% end %>

        <h1>User info</h1>
          <%= render 'users/user', user: @user %>

        <%= link_to edit_user_path(current_user.id), class: 'btn btn-outline-secondary btn-block', method: :get do %>
          <i class="fas fa-user-cog"></i>
        <% end %>

        <h3>New book</h3>
        <%= render 'books/book', book: @book %>
      </div>

      <div class="col-md-8 offset-md-1">
        <table class="table table-hover table-inverse">
          <h4>Books</h4>
          <thead>
            <th></th>
            <th>Title </th>
            <th>Opinion </th>

            <tr>
              <% @books.each do |book| %>
                <tr>
                  <th>
                    <%= link_to user_path(book.user) do %>
                      <%= image_tag @user.get_profile_image(100,100), fallback: "no_image.jpg" %>
                    <% end %>
                  </th>
                  <th><%= link_to book.title, book_path(book.id) %></th>
                  <th><%= book.body %></th>
                  <th id="favorite_buttons_<%= book.id %>">
                    <%= render 'books/favorites', book: book, user: current_user  %>
                  </th>
                  <th>コメント数：<%= book.book_comments.count %></th>
                </tr>
              <% end %>
            </tr>
          </thead>
        </table>
      </div>
    </div>
  </div>
</main>

app/views/books/show.html.erb
<main>
  <div class="container px-5 px-sm-0">
    <div class="row">
      <div class="col-md-3">
        <h1>User info</h1>
        <table class="table">
          <tbody>
            <tr>
              <th><%= image_tag @user.get_profile_image(100,100), fallback: "no_image.jpg" %></th>
            </tr>
            <tr>
              <th>name：<%= @user.name %></th>
            </tr>
            <tr>
              <th>introduction：<%= @user.introduction %></th>
            </tr>
          </tbody>
        </table>

        <%= link_to edit_user_path(@user.id), class: 'btn btn-outline-secondary btn-block', method: :get do %>
          <i class="fas fa-user-cog"></i>
        <% end %>

        <h3>New book</h3>
          <%= render 'books/book', book: @newbook %>
      </div>

      <div class="col-md-8 offset-md-1">
        <h4>Book detail</h4>
        <table class="table table-hover table-inverse">
          <thead>
              <th>
                <%= link_to user_path(@book.user) do %>
                  <%= image_tag @user.get_profile_image(100,100), fallback: "no_image.jpg" %><br>
                  <%= @book.user.name %>
　　　          <% end %>
　　　        </th>
              <th>
                <%= link_to @book.title, book_path(@book.id) %>
              </th>
              <th>
                <%= @book.body %>
              </th>
              <th id="favorite_buttons_<%= @book.id %>">
                <%= render 'books/favorites', book: @book, user: current_user  %>
              </th>
              <th>コメント数：<%= @book.book_comments.count %></th>
              <% if @user.id == current_user.id %>
                <th><%= link_to 'Edit', edit_book_path(@book.id), class: 'btn btn-success' %></th>
                <th><%= link_to "Destroy", book_path(@book.id), class: 'btn btn-danger', method: :delete, "data-confirm" => "Are you sure?" %></th>
              <% end %>
            </tr>
          </thead>
        </table>
        
        <div id="comments-area">
          <%= render "book_comments/comment",book: @book %>
        </div>
        
      　<div>
      　 <%= render "book_comments/form",book: @book,book_comment: @book_comment　%>
      　</div>
      </div>
    </div>
  </div>
</main>